### ISSUE TITLE
"jupyter" is not recognized

### ISSUE THREAD

**Issue by aluthfian** [simpeg-research/Astic-2020-JointInversion#3]
Hi,

I am Fian and I am interested in your work. I have cloned the GIT into my system, and when I tried to run it, it gives 

_'jupyter' is not recognized as an internal or external command,
operable program or batch file._

I have tried several things:

1. Copied the jupyter into the pgijoint-env folder,
2. Adding the Python Home Path to my System's Environment Variables,
3. Reinstalled Jupyter (which it says that it is already in my system).

I have ran out of ideas, can you offer me any other solution?

**Comment by thast** [comment]
Hi @aluthfian, thank you for your interest.
You indeed need to have `jupyter` installed. I would recommend using [`Anaconda`](https://www.anaconda.com/products/individual) for your `Python` environment. I believe `jupyter` comes with it by default. If not, you could then write in your command line `conda install jupyter`. You can create the `pgijoint-environment` similarly (see [page on anaconda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)). 
Edit: see also the [instructions in the Usage section of the Readme on the main page](https://github.com/simpeg-research/Astic-2020-JointInversion#usage)

Just in case, this implementation is done on top of the `python` package [`SimPEG`](https://simpeg.xyz/). I would suggest taking a look at it. Within its documentation, there is also a [turorial for getting started with `Python`](http://docs.simpeg.xyz/content/basic/installing.html).

I hope this is all helpful. Let me know if you encounter any further issue. This will help me update this repository in the future.

Bonus: just in case again, for the non-joint PGI approach (see [publication](https://doi.org/10.1093/gji/ggz389)), the examples were small enough that I could have them run on a [cloud](https://mybinder.org/v2/gh/simpeg-research/Astic-2019-PGI/master?filepath=index.ipynb). This removed the need for users to install anything. If this is something that is still of interest to you, or that you feel might be a good intermediate step, this is [the `GitHub` repository](https://github.com/simpeg-research/Astic-2019-PGI), and the[ mentioned cloud environment to run the examples ](https://mybinder.org/v2/gh/simpeg-research/Astic-2019-PGI/master?filepath=index.ipynb)(it can take several minutes to load).

**Comment by thast** [comment]
I am closing this issue after the following actions:
- updated the [instructions in the Usage section of the Readme for clarity](https://github.com/simpeg-research/Astic-2020-JointInversion#usage)
- added `jupyter notebook` as an explicit dependency in the environment and requirements files

Feel free to open another issue or reopen this one. If you are interested in connecting with the wider `SimPEG` community, we have a [`Slack Channel`](http://slack.simpeg.xyz/) and a [discourse](https://simpeg.discourse.group/)
