### ISSUE TITLE
module'SimPEG.regularization'has no attribute ''MakeSimplePetroRegularization'

### ISSUE THREAD

**Issue by ZhaoyangSU-CUP** [simpeg-research/Astic-2020-JointInversion#4]
hi ，i'm zhaoyang, you did excellent work.

i have a problem, when i try to run PGI_joint_no_petrophysical_means_information.ipynb, it gives 

module'SimPEG.regularization'has no attribute ''MakeSimplePetroRegularization'

my simpeg version is 0.13.0.  How can I solve this problem？

appreciate.

**Comment by thast** [comment]
Hi @ZhaoyangSU-CUP, 
Thank you for your interest.

To run these notebooks, you need to run `SimPEG` from a specific branch (PGI is not yet part of the main distribution, but it will be in the next few months). The branch is `examples/PGI_joint`

If you are not sure how to do that, please [follow the instructions in the README.md, section USAGE](https://github.com/simpeg-research/Astic-2020-JointInversion#usage).

Please free to contact me again if you encounter any issues; your feedbacks are valuable to improve this repository.

PS: is this error is resolved by switching branch, I will be closing this issue, but feel free to create a new one.
