### ISSUE TITLE
I couldn't recreate the ocTree mesh input file exactly

### ISSUE THREAD

**Issue by ramaarksuri** [simpeg-research/Astic-2020-JointInversion#8]
1. I tried to recreate the ocTree mesh data file used in the Joint PGI of Gravity and Magnetic without petrophysical information code. However, I was unable to create the precise ocTree mesh file. Please specify the exact parameters for reproducing the Octree mesh data file.
I have attached the code for creating an ocTree mesh file and cross-sections and XY plots of the ocTree mesh.
####### create octree mesh file 
# Import Modules

import numpy as np
from scipy.interpolate import LinearNDInterpolator
import matplotlib as mpl
import matplotlib.pyplot as plt

from discretize import TreeMesh
from discretize.utils import mkvc, refine_tree_xyz
from SimPEG.utils import plot2Ddata, model_builder, surface2ind_topo
from SimPEG import maps
from SimPEG.potential_fields import gravity

######### load topogaphy data #########################

data1 = np.genfromtxt('TOPO_AOI_KIMBERLITE_CANADA_15JUL21.dat')
                     
x_topo1=data1[:, 0]
x_topo2= np.transpose(x_topo1)
y_topo1=data1[:, 1]
y_topo2= np.transpose(y_topo1)
z_topo1=data1[:, 2]
z_topo2= np.transpose(z_topo1)

x_topo, y_topo, z_topo = mkvc(x_topo2), mkvc(y_topo2), mkvc(z_topo2)
xyz_topo = np.c_[x_topo, y_topo, z_topo ]

#Defining an OcTree Mesh

dx = 25  # minimum cell width (base mesh cell width) in x
dy = 25  # minimum cell width (base mesh cell width) in y
dz = 25  # minimum cell width (base mesh cell width) in z

x_length = 800.0  # domain width in x
y_length = 800.0  # domain width in y
z_length = 800.0  # domain width in z

# Compute number of base mesh cells required in x and y
nbcx = 2 ** int(np.round(np.log(x_length / dx) / np.log(2.0)))
nbcy = 2 ** int(np.round(np.log(y_length / dy) / np.log(2.0)))
nbcz = 2 ** int(np.round(np.log(z_length / dz) / np.log(2.0)))

# Define the base mesh
hx = [(dx, nbcx)]
hy = [(dy, nbcy)]
hz = [(dz, nbcz)]

#mesh = TreeMesh([hx, hy, hz]) 
mesh = TreeMesh([hx, hy, hz], x0="CCN")

xc = 400 + 556900
yc = 400 + 7133200
zc = 440.9

x0_new = np.r_[mesh.x0[0] + xc, mesh.x0[1] + yc, mesh.x0[2] + zc]

mesh.x0 = x0_new

# Refine based on surface topography
mesh = refine_tree_xyz(
    mesh, xyz_topo, octree_levels=[2, 2], method="surface", finalize=False
)

# Refine box based on region of interest

xp, yp, zp = np.meshgrid([557000.0, 557600.0], [7133300.0, 7133900.0], [50.0, 400.0])
xyz = np.c_[mkvc(xp), mkvc(yp), mkvc(zp)]
mesh = refine_tree_xyz(mesh, xyz, octree_levels=[2, 2], method="box", finalize=False)

mesh.finalize()

mesh.writeUBC('mesh_file1.ubc')
![image](https://user-images.githubusercontent.com/41540558/125897703-e92b80ee-10cc-4bf4-a53b-70b7519e5ff1.png)

2. I was unable to construct correct output quasi-geological model or density/susceptibility contrast on cross-sections and XY plots, and 2D density probability plot using the Joint PGI of Gravity and Magnetic without petrophysical information code with the ocTree mesh file that I created using the preceding script (remaining input files and settings are the same). Please find the attached figures.
![cross_plots_v315jul21](https://user-images.githubusercontent.com/41540558/125897631-2d19fe6a-4dbe-43c6-b239-486e0fb75e8a.png)
![denssity_probability_15jul21](https://user-images.githubusercontent.com/41540558/125897770-e39208c4-da46-422a-8f89-b9e6c596e76e.png)

3. I noticed no quasi-geological model or density/susceptibility contrast on cross-sections and XY plots, and the points on the density probability plot are scattered, I am not sure why.

**Comment by thast** [comment]
Hi @ramaarksuri ,

Can you try to download the tutorial, either as a Python script `.py` or a jupyter notebook `.ipynb` and run it unchanged on your local machine? You must be on `SimPEG>=0.15.0` and `discretize>0.7.0`.

Once you can successfully run the unchanged tutorial script, you can start modifying it to your needs.

![image](https://user-images.githubusercontent.com/13682747/125996860-9f2c30e5-6160-4aa1-bd6f-dd844ffbb0a4.png)


Note: 
- The tutorial is using a Octree mesh, while this repository uses a TensorMesh. TensorMesh simulation are slower as they usually requires more cells. The reason I used a Tensor in this repository is that I did this work before Octree was properly implemented in `discretize`. 
- This repository is important for reproducibility and archive, it is meant to capture a static picture of this work (minus bugs fixes and typos of course). As such it uses an older syntax of SimPEG and it is not meant to be maintained with regards to every SimPEG change and development. I would encourage you to base your work on the tutorials, which use all the latest  syntax and features (and will be maintained to be up to date with any future development of SimPEG and discretize).

**Comment by ramaarksuri** [comment]
- Thank you for your response; nevertheless, I believe I have not adequately communicated my query regarding the creation of an ocTree mesh data file.
- With my local machine, I was able to replicate the same results of the tutorial code (plot_inv_2_joint_pf_pgi_no_info_tutorial.py).
- Now,  I tried to recreate the exact ocTree mesh data file that was used in the tutorial code (plot_inv_2_joint_pf_pgi_no_info_tutorial.py). However, I was unable to create the precise ocTree mesh file. Please provide exact parameters for recreating the Octree mesh data file.
- If I used the ocTree mesh file that was created by the following code as an input file to the tutorial code (remaining input files and settings are the same), I was unable to reproduce the correct results of the tutorial code (plot_inv_2_joint_pf_pgi_no_info_tutorial.py)
- Please check the script I used to create an ocTree mesh file.
####### create octree mesh file ###############################
##Import Modules

import numpy as np
from scipy.interpolate import LinearNDInterpolator
import matplotlib as mpl
import matplotlib.pyplot as plt

from discretize import TreeMesh
from discretize.utils import mkvc, refine_tree_xyz
from SimPEG.utils import plot2Ddata, model_builder, surface2ind_topo
from SimPEG import maps
from SimPEG.potential_fields import gravity

######### load topogaphy data #########################

data1 = np.genfromtxt('TOPO_DATA.dat')                     
x_topo1=data1[:, 0]
x_topo2= np.transpose(x_topo1)
y_topo1=data1[:, 1]
y_topo2= np.transpose(y_topo1)
z_topo1=data1[:, 2]
z_topo2= np.transpose(z_topo1)

x_topo, y_topo, z_topo = mkvc(x_topo2), mkvc(y_topo2), mkvc(z_topo2)
xyz_topo = np.c_[x_topo, y_topo, z_topo ]

##Defining an OcTree Mesh

dx = 25  # minimum cell width (base mesh cell width) in x
dy = 25  # minimum cell width (base mesh cell width) in y
dz = 25  # minimum cell width (base mesh cell width) in z

x_length = 800.0  # domain width in x
y_length = 800.0  # domain width in y
z_length = 800.0  # domain width in z

##Compute number of base mesh cells required in x and y
nbcx = 2 ** int(np.round(np.log(x_length / dx) / np.log(2.0)))
nbcy = 2 ** int(np.round(np.log(y_length / dy) / np.log(2.0)))
nbcz = 2 ** int(np.round(np.log(z_length / dz) / np.log(2.0)))

##Define the base mesh
hx = [(dx, nbcx)]
hy = [(dy, nbcy)]
hz = [(dz, nbcz)]

mesh = TreeMesh([hx, hy, hz], x0="CCN")

xc = 400 + 556900
yc = 400 + 7133200
zc = 440.9

x0_new = np.r_[mesh.x0[0] + xc, mesh.x0[1] + yc, mesh.x0[2] + zc]
mesh.x0 = x0_new

##Refine based on surface topography
mesh = refine_tree_xyz(
    mesh, xyz_topo, octree_levels=[2, 2], method="surface", finalize=False
)

##Refine box based on the region of interest

xp, yp, zp = np.meshgrid([557000.0, 557600.0], [7133300.0, 7133900.0], [50.0, 400.0])
xyz = np.c_[mkvc(xp), mkvc(yp), mkvc(zp)]
mesh = refine_tree_xyz(mesh, xyz, octree_levels=[2, 2], method="box", finalize=False)

##Refine mesh near points
xx = np.array([556900, 557700, 25])
yy = np.array([7133200, 7134000, 25])
pts = np.c_[mkvc(xx), mkvc(yy)]
mesh = refine_tree_xyz(mesh, pts, octree_levels=[2, 2], method="radial", finalize=False)
mesh.finalize()

mesh.writeUBC('mesh_file_1.ubc')

- Please see the attached cross-sections and XY plots of quasi-geological model and density/susceptibility contrast and the density probability plot

![cross_plots_v315jul21](https://user-images.githubusercontent.com/41540558/126027491-a4e96938-6d6c-4ee7-99ef-616ac799f89a.png)
![denssity_probability_15jul21](https://user-images.githubusercontent.com/41540558/126027527-c409e03a-4610-46e1-8ece-56ee5b0aa9cb.png)

Thank you so much for your assistance

**Comment by thast** [comment]
Here is the script I used to create the octree mesh. I just re-ran it using `discretize 0.7.0`and it only differs by a couple of cells from the original; those differences do not matter (the original mesh file was likely created with `discretize 0.6.X`). If you want to interpolate the models provided in the tutorial with the new mesh, you could use the `NearestNDInterpolator` tool provided by `scipy`.
[TKC_modeling_MeshCreation-ForTutorial-Sharing.ipynb.zip](https://github.com/simpeg-research/Astic-2020-JointInversion/files/6835202/TKC_modeling_MeshCreation-ForTutorial-Sharing.ipynb.zip)

Just looking at your figure with the geology model cross-sections, I would imagine there is an issue with the definition of the active cells; the topography seems to cut the mode way below what it is supposed to. The figure of your mesh looks fine at first glance. I added the definition of active cells in my script. A couple of guesses: the problem you have could be either in the definition of the topo object, or be due to a difference of georeferencing between the mesh and the topo.

Note:
- this mesh is purposely very small, to keep the run time of this tutorial as low as possible. For practical application, you would likely want to use a finer discretization and more padding.
- The creation of the mesh and models is not part of the tutorial to keep the tutorial as light and focused as possible; there are other tutorials that focus on those points (that I am sure you have seen to create your script ; I am just providing this note for other potential readers).

**Comment by ramaarksuri** [comment]
Thank you so much for responding and taking the time to clarify my questions
